CREATE TABLE IF NOT EXISTS study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic TEXT NOT NULL DEFAULT 'General Study',
    duration_minutes INTEGER NOT NULL,
    focus_rating INTEGER NOT NULL DEFAULT 4 CHECK (focus_rating >= 1 AND focus_rating <= 5),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_sessions_created_at ON study_sessions (created_at DESC);

CREATE TABLE IF NOT EXISTS daily_goals (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    target_minutes INTEGER NOT NULL DEFAULT 120,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    tool_calls JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_session ON agent_memory (session_id, id DESC);

ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write on study_sessions" ON study_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write on daily_goals" ON daily_goals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write on agent_memory" ON agent_memory FOR ALL USING (true) WITH CHECK (true);
