-- Multi-Tenant Study Coach Supabase Schema with User Isolation & Psychological Schedules

CREATE TABLE IF NOT EXISTS user_schedules (
    user_id TEXT PRIMARY KEY,
    name TEXT DEFAULT 'Student',
    wake_time TEXT DEFAULT '07:00',
    sleep_time TEXT DEFAULT '23:00',
    peak_energy_window TEXT DEFAULT 'morning',
    fixed_commitments TEXT DEFAULT '',
    target_exam_or_goal TEXT DEFAULT '',
    preferred_pomodoro_length INTEGER DEFAULT 25,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS study_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default-student',
    topic TEXT NOT NULL DEFAULT 'General Study',
    duration_minutes INTEGER NOT NULL,
    focus_rating INTEGER NOT NULL DEFAULT 4 CHECK (focus_rating >= 1 AND focus_rating <= 5),
    notes TEXT DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_study_sessions_user_date ON study_sessions (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS daily_goals (
    user_id TEXT NOT NULL DEFAULT 'default-student',
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    target_minutes INTEGER NOT NULL DEFAULT 120,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, date)
);

CREATE TABLE IF NOT EXISTS agent_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'default-student',
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    tool_calls JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_user_session ON agent_memory (user_id, session_id, id DESC);

ALTER TABLE user_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_memory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write on user_schedules" ON user_schedules FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write on study_sessions" ON study_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write on daily_goals" ON daily_goals FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read-write on agent_memory" ON agent_memory FOR ALL USING (true) WITH CHECK (true);

